# Generated by Django 4.1.2 on 2022-10-21 12:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='A nick name for your vehicle', max_length=1000)),
                ('vin_number', models.CharField(help_text='Vehicle identification number', max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('start_address', models.CharField(max_length=5000)),
                ('end_address', models.CharField(max_length=5000)),
                ('distance', models.FloatField()),
                ('energy_consumption', models.FloatField()),
                ('category', models.CharField(max_length=200)),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('end_latitude', models.FloatField()),
                ('end_longitude', models.FloatField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.vehicle')),
            ],
        ),
    ]
